### ISSUE TITLE
Gradle Implementation

### ISSUE THREAD

**Issue by Tux8068** [mlieshoff/jcrapi2#132]
could you add a gradle implementation please

**Comment by mlieshoff** [comment]
@Tux8068 hey, sure, can you give  bit more details please? FYI you can easy include the jar in gradle as a depency

**Comment by mlieshoff** [comment]
maybe that helps you out? 
`
implementation group: 'jcrapi2', name: 'jcrapi2', version: '1.0.4'
`

**Comment by Tux8068** [comment]
Yes thanks

**Comment by mlieshoff** [comment]
great, it will be added to the readme

**Comment by mlieshoff** [comment]
done
